# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 899d4aa6c33f5251a5d2a8f59a6ab8bff46e3c100609ae820f47c83e734ca8245116845e97464afb208e9ba5d1839a54d0ea735a7a83e91f4d26b4244fd9ac97

test:
  secret_key_base: 4ddd939ff7b957540a86ae420aacfbecc08c6a50202b87fc16263aacfa42a578b890778ad2b4343bb907cbc817299fefa9313c61c85800a470f3ca93d8bc02cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
